import { integer, pgTable, varchar, text, boolean,uuid } from 'drizzle-orm/pg-core'; 

export const registerTable2 = pgTable('supplier_details', {
  id: uuid('id').primaryKey().defaultRandom(),
  vehicle_type: text('vehicle_type').notNull(),
  vehicle_brand: text('vehicle_brand').notNull(),
  type_service: varchar({ length: 255 }).notNull(),
  vehicle_model: integer().notNull(), 
  doors: varchar({ length: 255 }).notNull(), 
  seats: varchar({length:255}).notNull(),
  category_space: integer(),
  max_number_pax_accommodate: varchar({ length: 255 }).notNull(),
  luggage_information: varchar({length:255}).notNull(),
  max_number_medium_suitcase: varchar({ length:255 }).notNull(),
  max_number_carbin_bag: varchar({length:255}).notNull(), 
  space_available_other_luggage: integer().notNull(), 
  location_details: varchar({ length: 255 }).notNull(),
  transfer_information: varchar({ length: 255 }).notNull(),
  service_providing_location: varchar({length:255}).notNull(),  
  airport: varchar({length:255}).notNull(),
  port_cruise: varchar({length:255}).notNull(),
  station: varchar({length:255}).notNull(),
  city_center: varchar({length:255}).notNull(),
  vehicle_for: varchar({length:255}).notNull(),
  half_day_city_limit_4hrs: boolean('half_day_city_limit_4hrs').default(false), 
  full_day_city_limit_8hrs: boolean('half_day_city_limit_8hrs').default(false), 
  inclusions: boolean().default(true),
  vehicle_rent: integer().notNull(),
  fuel: varchar({length:255}).notNull(),
  driver: varchar({length:255}).notNull(),
  parking_fees: integer().notNull(),
  toll_or_taxes: integer().notNull(), 
  driver_tips: integer().notNull(),
  other: varchar({length:255}).notNull(), 
});

