import { integer, pgTable, varchar, text, PgTable, date } from 'drizzle-orm/pg-core'; 

export const registerTable = pgTable('supplier', {
  id: integer().primaryKey().generatedAlwaysAsIdentity(),
  company_name_or_owns_car: varchar({ length: 255 }).notNull(),
  owner_name: varchar({ length: 255 }).notNull(),
  office_address: varchar({ length: 255 }).notNull(),
  country: varchar({ length: 255 }).notNull(), 
  city: varchar({ length: 255 }).notNull(),
  zipcode: varchar({length:255}).notNull(),
  office_number: varchar({length:255}).notNull(),
  email: varchar({ length: 255 }).notNull().unique(),
  contact_person: varchar({length:255}).notNull(),
  mobile_number: varchar({length:255}).notNull(),
  tax_no_or_vat_no: varchar({length:255}).notNull(), 
  pan_number: varchar({length:255}).notNull(), 
  currency: varchar({ length: 255 }).notNull(),
  image: varchar({ length: 255 }).notNull(),
  password: varchar({length:255}).notNull(),
  api_key:varchar({length:255}).notNull(),
  is_up:varchar({length:255}).notNull(),
  // imagepath: text('image_path').notNull(),  
});

export const One_WayTable = pgTable('One_Way_Service_Details',{
    id:integer().primaryKey().generatedAlwaysAsIdentity(),
    country:varchar({length:255}).notNull(),
    city:varchar({length:255}).notNull(),
    location_from_airport:varchar({length:255}).notNull(),
    location_from_port_cruise:varchar({length:255}).notNull(),
    location_from_station:varchar({length:255}).notNull(),
    location_from_city_center:varchar({length:255}).notNull(),
    location_to_airport:varchar({length:255}).notNull(),
    location_to_port_cruise:varchar({length:255}).notNull(),
    location_to_station:varchar({length:255}).notNull(),
    location_to_city_center:varchar({length:255}).notNull(),
    night_time_supplement:varchar({length:255}).notNull(),
    vice_versa:varchar({length:255}).notNull(),
    half_day_city_limit_4hrs:varchar({length:255}).notNull(),
    full_day_city_limit_8hrs:varchar({length:255}).notNull(),
    from_date: date().notNull(), 
    to_date: date().notNull(),   
    price: integer().notNull(), 
    new_location: varchar({ length: 255 }).notNull(),

});

export const Roundtrip_Service_Price_Details = pgTable('Roundtrip_Service_Price_Details',{
  id:integer().primaryKey().generatedAlwaysAsIdentity(),
  country:varchar({length:255}).notNull(),
  city:varchar({length:255}).notNull(),
  location_from_airport:varchar({length:255}).notNull(),
  location_from_port_cruise:varchar({length:255}).notNull(),
  location_from_station:varchar({length:255}).notNull(),
  location_from_city_center:varchar({length:255}).notNull(),
  location_to_airport:varchar({length:255}).notNull(),
  location_to_port_cruise:varchar({length:255}).notNull(),
  location_to_station:varchar({length:255}).notNull(),
  location_to_city_center:varchar({length:255}).notNull(),
  night_time_supplement:varchar({length:255}).notNull(),
  vice_versa:varchar({length:255}).notNull(),
  half_day_city_limit_4hrs:varchar({length:255}).notNull(), 
  full_day_city_limit_8hrs:varchar({length:255}).notNull(),
  from_date: date().notNull(), 
  to_date: date().notNull(),   
  price: integer().notNull(), 
  new_location: varchar({ length: 255 }).notNull(), 
}); 