CREATE TABLE IF NOT EXISTS "One_Way_Service_Details" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "One_Way_Service_Details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"country" varchar(255) NOT NULL,
	"city" varchar(255) NOT NULL,
	"location_from_airport" varchar(255) NOT NULL,
	"location_from_port_cruise" varchar(255) NOT NULL,
	"location_from_station" varchar(255) NOT NULL,
	"location_from_city_center" varchar(255) NOT NULL,
	"location_to_airport" varchar(255) NOT NULL,
	"location_to_port_cruise" varchar(255) NOT NULL,
	"location_to_station" varchar(255) NOT NULL,
	"location_to_city_center" varchar(255) NOT NULL,
	"night_time_supplement" varchar(255) NOT NULL,
	"vice_versa" varchar(255) NOT NULL,
	"half_day_city_limit_4hrs" varchar(255) NOT NULL,
	"full_day_city_limit_8hrs" varchar(255) NOT NULL,
	"from_date" date NOT NULL,
	"to_date" date NOT NULL,
	"price" integer NOT NULL,
	"new_location" varchar(255) NOT NULL
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "Roundtrip_Service_Price_Details" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "Roundtrip_Service_Price_Details_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"country" varchar(255) NOT NULL,
	"city" varchar(255) NOT NULL,
	"location_from_airport" varchar(255) NOT NULL,
	"location_from_port_cruise" varchar(255) NOT NULL,
	"location_from_station" varchar(255) NOT NULL,
	"location_from_city_center" varchar(255) NOT NULL,
	"location_to_airport" varchar(255) NOT NULL,
	"location_to_port_cruise" varchar(255) NOT NULL,
	"location_to_station" varchar(255) NOT NULL,
	"location_to_city_center" varchar(255) NOT NULL,
	"night_time_supplement" varchar(255) NOT NULL,
	"vice_versa" varchar(255) NOT NULL,
	"half_day_city_limit_4hrs" varchar(255) NOT NULL,
	"full_day_city_limit_8hrs" varchar(255) NOT NULL,
	"from_date" date NOT NULL,
	"to_date" date NOT NULL,
	"price" integer NOT NULL,
	"new_location" varchar(255) NOT NULL
);
