export interface CreateSupplierDetailServicesInput { 
<<<<<<< HEAD
<<<<<<< HEAD
 vehicle_type:Text,
  vehicle_brand:Text, 
  type_service:string,
  vehicle_model:number, 
  doors:string,
  seats:string,
  category_space:number,
  max_number_pax_accommodate:string,
  luggage_information:string,
  max_number_medium_suitcase:string,
  max_number_carbin_bag:string, 
  space_available_other_luggage:number, 
  location_details:string,
  transfer_information:string,
  service_providing_location:string,  
  airport:string,
  port_cruise:string, 
  station:string,
  city_center:string,
  vehicle_for:string,
  half_day_city_limit_4hrs: boolean, 
  full_day_city_limit_8hrs: boolean,   
  inclusions:boolean,
  vehicle_rent:number,
  fuel:string,
  driver:string,
  parking_fees:number,
  toll_or_taxes:number, 
  driver_tips:number,
  other:string, 
=======
=======
>>>>>>> develop
  Vehicle_type: string,
  Vehicle_brand: string, 
  Type_service:string,
  Vehicle_model: string, 
  Doors:string,
  Seats:string,
  Category_space:string,
  Max_number_pax_accommodate:string,
  Luggage_information:string,
  Max_number_medium_suitcase:string,
  Max_number_carbin_bag:string, 
  Space_available_other_luggage:string, 
  Location_details:string,
  Transfer_information:string,
  Service_providing_location:string,  
  Airport:string,
  Port_cruise:string, 
  Station:string,
  City_center:string,
  Vehicle_for:string,
  Half_day_city_limit_4hrs: string, 
  Full_day_city_limit_8hrs: string,   
  Inclusions:string,
  Vehicle_rent:string,
  Fuel:string,
  Driver:string,
  Parking_fees:string,
  Toll_or_taxes:string, 
  Driver_tips:string,
  Other:string, 
<<<<<<< HEAD
>>>>>>> Supplier
=======
>>>>>>> develop
  } 